[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "chromiumoxide-bindings"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[tool.maturin]
# The Rust crate name must match [lib] name in Cargo.toml
module-name = "chromiumoxide_py"
# Build in release mode (recommended for distribution)
profile = "release"
