# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = []

@typing.final
class _AddScriptToEvaluateOnNewDocumentParams:
    @property
    def source(self) -> builtins.str: ...
    @property
    def include_command_line_api(self) -> typing.Optional[builtins.bool]: ...
    @property
    def world_name(self) -> typing.Optional[builtins.str]: ...
    @property
    def run_immediately(self) -> typing.Optional[builtins.bool]: ...
    def __new__(cls, source: builtins.str, include_command_line_api: typing.Optional[builtins.bool] = None, world_name: typing.Optional[builtins.str] = None, run_immediately: typing.Optional[builtins.bool] = None) -> _AddScriptToEvaluateOnNewDocumentParams: ...

@typing.final
class _Browser:
    @staticmethod
    def launch(config: _BrowserConfig) -> _Browser: ...
    def new_page(self, url: builtins.str) -> _Page: ...
    def close(self) -> None: ...
    def websocket_address(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class _BrowserConfig:
    r"""
    A finalised browser launch configuration.
    
    Create via ``BrowserConfig.builder()`` (class-method shorthand) or
    directly via ``BrowserConfigBuilder``::
    
        cfg = BrowserConfig.builder().build()   # minimal
    
    Each `BrowserConfig` may only be used **once** – it is consumed by
    ``Browser.launch``.
    """
    @staticmethod
    def builder() -> _BrowserConfigBuilder:
        r"""
        Convenience shorthand: ``BrowserConfig.builder()`` returns a
        `BrowserConfigBuilder`.
        """
    @staticmethod
    def default() -> _BrowserConfig: ...

@typing.final
class _BrowserConfigBuilder:
    r"""
    Fluent builder for `BrowserConfig`.
    
    Example::
    
        builder = BrowserConfigBuilder()
        builder.chrome_executable("/usr/bin/chromium")
        builder.no_sandbox()
        cfg = builder.build()
    """
    def __new__(cls) -> _BrowserConfigBuilder: ...
    def chrome_executable(self, path: builtins.str) -> None:
        r"""
        Set the path to the Chrome/Chromium executable.
        """
    def with_head(self) -> None:
        r"""
        Show a browser window instead of running headlessly.
        """
    def no_sandbox(self) -> None:
        r"""
        Disable the Chrome sandbox (needed in many Docker/container setups).
        """
    def arg(self, arg: builtins.str) -> None:
        r"""
        Append an extra CLI argument passed directly to the Chrome process.
        """
    def window_size(self, width: builtins.int, height: builtins.int) -> None:
        r"""
        Set the browser window dimensions (pixels).
        """
    def user_data_dir(self, path: builtins.str) -> None:
        r"""
        Set the Chrome user-data directory (for profile persistence).
        """
    def build(self) -> _BrowserConfig:
        r"""
        Build a ready-to-use `BrowserConfig`.
        
        Raises `ValueError` if the configuration is invalid.
        """

@typing.final
class _Element:
    def click(self) -> _Element:
        r"""
        Click the element.  Returns self.
        """
    def type_str(self, text: builtins.str) -> _Element:
        r"""
        Type `text` into the element (focuses it first).  Returns self.
        """
    def press_key(self, key: builtins.str) -> _Element:
        r"""
        Dispatch a key-press event (e.g. ``"Enter"``, ``"Tab"``, ``"Escape"``).
        
        Returns self.
        """
    def inner_text(self) -> typing.Optional[builtins.str]:
        r"""
        Return the element's visible text (``innerText``), or ``None``.
        """
    def inner_html(self) -> typing.Optional[builtins.str]:
        r"""
        Return the element's raw HTML (``innerHTML``), or ``None``.
        """
    def attribute(self, name: builtins.str) -> typing.Optional[builtins.str]:
        r"""
        Return the value of attribute `name`, or ``None`` if not present.
        """
    def scroll_into_view(self) -> None:
        r"""
        Scroll this element into the viewport.
        """
    def focus(self) -> None:
        r"""
        Give keyboard focus to this element.
        """
    def find_element(self, selector: builtins.str) -> _Element:
        r"""
        Find a child element matching `selector` within this element's subtree.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class _Page:
    def goto(self, url: builtins.str) -> _Page:
        r"""
        Navigate to `url`.  Blocks until the page finishes loading.
        
        Returns self (for chaining).
        """
    def wait_for_navigation(self) -> _Page:
        r"""
        Block until the next navigation event completes.
        
        Returns self so you can chain `.content()`::
        
            html = page.wait_for_navigation().content()
        """
    def reload(self) -> _Page:
        r"""
        Reload the current page and wait for navigation.
        
        Returns self.
        """
    def content(self) -> builtins.str:
        r"""
        Return the full outer HTML of the current document.
        """
    def set_content(self, html: builtins.str) -> None:
        r"""
        Replace the entire page content with the given HTML string.
        """
    def title(self) -> typing.Optional[builtins.str]:
        r"""
        Return the document ``<title>`` or ``None``.
        """
    def url(self) -> typing.Optional[builtins.str]:
        r"""
        Return the current URL or ``None``.
        """
    def evaluate(self, expression: builtins.str) -> builtins.str:
        r"""
        Evaluate a JavaScript expression or arrow-function body.
        
        Returns the result as a JSON-encoded string.
        
        Example::
        
            page.evaluate("1 + 2")            # "3"
            page.evaluate("() => 'hello'")    # '"hello"'
            page.evaluate("document.title")   # '"My Page"'
        """
    def add_script_to_evaluate_on_new_document(self, params: _AddScriptToEvaluateOnNewDocumentParams) -> builtins.str: ...
    def remove_script_to_evaluate_on_new_document(self, identifier: builtins.str) -> None: ...
    def enable_stealth_mode(self) -> None: ...
    def screenshot(self) -> builtins.list[builtins.int]: ...
    def pdf(self, landscape: builtins.bool = False) -> builtins.list[builtins.int]:
        r"""
        Render the page to a PDF and return the raw bytes.
        
        Args:
            landscape (bool): Use landscape orientation.  Default ``False``.
        """
    def find_element(self, selector: builtins.str) -> _Element:
        r"""
        Return the first DOM element matching the CSS `selector`.
        
        Raises `RuntimeError` if no element matches.
        """
    def find_elements(self, selector: builtins.str) -> builtins.list[_Element]:
        r"""
        Return all DOM elements matching the CSS `selector`.
        """
    def set_user_agent(self, user_agent: builtins.str) -> None:
        r"""
        Override the User-Agent header sent with every request.
        """
    def cookies(self) -> builtins.str:
        r"""
        Return the cookies visible to the current URL as a JSON string.
        """
    def close(self) -> None:
        r"""
        Close this tab.
        """
    def __repr__(self) -> builtins.str: ...

