# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
from . import browser
__all__ = [
    "Page",
    "browser",
]

@typing.final
class Page:
    def enable_stealth_mode(self) -> None: ...
    def enable_stealth_mode_with_agent(self, ua: builtins.str) -> None: ...
    def goto(self, url: builtins.str) -> Page: ...
    def execute(self, command: typing.Any) -> None: ...
    def url(self) -> builtins.str: ...

